# Generated by Django 3.0.1 on 2022-05-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentNumber', models.CharField(max_length=500)),
                ('DueAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=500)),
                ('IsActive', models.BooleanField()),
                ('Pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Payments')),
            ],
        ),
    ]
